name: dev.yml
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'sdk'

      - name: Compile Java sources
        run: javac -d out $(find src -name "*.java")

      - name: Run tests
        run: java -cp out main.TestMain
